- id: circleci_validate
  name: Validate CircleCI config
  description: This hook validate CircleCI config 
  entry: circleci_validate.sh
  language: script
  files: ^.circleci/config.yml$
- id: gitlabci_validate
  name: Validate GitlabCI config
  description: This hook validate GitlabCI config
  entry: gitlabci_validate.sh
  language: script
  files: ^.gitlab-ci.yml$

